# Generated by Django 6.0.3 on 2026-03-24 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('input_file', models.FileField(upload_to='uploads/')),
                ('mass', models.FloatField()),
                ('angle_deg', models.FloatField(default=70.0)),
                ('v0', models.FloatField(default=0.0)),
                ('x0', models.FloatField(default=0.0)),
                ('t_max', models.FloatField(default=0.15)),
                ('dt', models.FloatField(default=0.0001)),
                ('x_max', models.FloatField(blank=True, null=True)),
                ('v_max', models.FloatField(blank=True, null=True)),
                ('x_final', models.FloatField(blank=True, null=True)),
                ('v_final', models.FloatField(blank=True, null=True)),
                ('a_final', models.FloatField(blank=True, null=True)),
                ('recoil_end_time', models.FloatField(blank=True, null=True)),
                ('return_end_time', models.FloatField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
        migrations.CreateModel(
            name='MagneticBrakeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('gamma', models.FloatField()),
                ('delta', models.FloatField()),
                ('xm', models.FloatField()),
                ('ym', models.FloatField()),
                ('dh1', models.FloatField()),
                ('dh2', models.FloatField()),
                ('dm', models.FloatField()),
                ('n', models.IntegerField()),
                ('mu', models.FloatField()),
                ('bz', models.FloatField()),
                ('lya', models.FloatField(default=2.5)),
                ('wn0', models.FloatField(default=1.0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brakes', to='recoil_app.calculationrun')),
            ],
        ),
    ]
