# Generated by Django 6.0.3 on 2026-03-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrun',
            name='plot_a_t',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_fmag_v',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_forces_main',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_forces_secondary',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_v_t',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_v_x',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_x_t',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
    ]
