# Generated by Django 6.0.3 on 2026-03-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0002_calculationrun_plot_a_t_calculationrun_plot_fmag_v_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrun',
            name='plot_v_a_t',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
    ]
