# Generated by Django 6.0.3 on 2026-03-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0003_calculationrun_plot_v_a_t'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculationrun',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запуск расчёта', 'verbose_name_plural': 'Запуски расчёта'},
        ),
        migrations.AlterModelOptions(
            name='magneticbrakeconfig',
            options={'ordering': ['run', 'index'], 'verbose_name': 'Параметры магнитного тормоза', 'verbose_name_plural': 'Параметры магнитных тормозов'},
        ),
    ]
