# Generated by Django 6.0.3 on 2026-03-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0004_alter_calculationrun_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationrun',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
