# Generated by Django 6.0.3 on 2026-03-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0005_alter_calculationrun_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrun',
            name='plot_forces_main_recoil',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_forces_main_return',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_forces_secondary_recoil',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_forces_secondary_return',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_v_t_recoil',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_v_t_return',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_x_t_recoil',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_x_t_return',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AlterField(
            model_name='calculationrun',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
