# Generated by Django 6.0.3 on 2026-03-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0006_calculationrun_plot_forces_main_recoil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrun',
            name='plot_v_a_t_recoil',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plot_v_a_t_return',
            field=models.ImageField(blank=True, null=True, upload_to='plots/'),
        ),
    ]
