# Generated by Django 6.0.3 on 2026-03-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0007_calculationrun_plot_v_a_t_recoil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrun',
            name='ext_out_of_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='spring_out_of_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='termination_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='warnings_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
