# Generated by Django 6.0.3 on 2026-03-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0008_calculationrun_ext_out_of_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationrun',
            name='ext_out_of_range',
        ),
    ]
