# Generated by Django 6.0.3 on 2026-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0009_remove_calculationrun_ext_out_of_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_a_t',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_fmag_v',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_forces_main',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_forces_main_recoil',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_forces_main_return',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_forces_secondary',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_forces_secondary_recoil',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_forces_secondary_return',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_v_a_t',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_v_a_t_recoil',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_v_a_t_return',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_v_t',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_v_t_recoil',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_v_t_return',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_v_x',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_x_t',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_x_t_recoil',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='plotly_x_t_return',
            field=models.FileField(blank=True, null=True, upload_to='plots/'),
        ),
    ]
