# Generated by Django 6.0.3 on 2026-03-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0010_calculationrun_plotly_a_t_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_a_t',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_fmag_v',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_forces_main',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_forces_main_recoil',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_forces_main_return',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_forces_secondary',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_forces_secondary_recoil',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_forces_secondary_return',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_v_a_t',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_v_a_t_recoil',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_v_a_t_return',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_v_t',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_v_t_recoil',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_v_t_return',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_v_x',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_x_t',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_x_t_recoil',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plot_x_t_return',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_a_t',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_fmag_v',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_forces_main',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_forces_main_recoil',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_forces_main_return',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_forces_secondary',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_forces_secondary_recoil',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_forces_secondary_return',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_v_a_t',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_v_a_t_recoil',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_v_a_t_return',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_v_t',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_v_t_recoil',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_v_t_return',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_v_x',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_x_t',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_x_t_recoil',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='plotly_x_t_return',
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_a_t',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_fmag_v',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_forces_main',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_forces_main_recoil',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_forces_main_return',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_forces_secondary',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_forces_secondary_recoil',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_forces_secondary_return',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_v_a_t',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_v_a_t_recoil',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_v_a_t_return',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_v_t',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_v_t_recoil',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_v_t_return',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_v_x',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_x_t',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_x_t_recoil',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='chart_x_t_return',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
