# Generated by Django 6.0.3 on 2026-03-31 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0011_remove_calculationrun_plot_a_t_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationrun',
            name='chart_a_t',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='chart_forces_main',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='chart_v_t',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='chart_v_t_recoil',
        ),
        migrations.RemoveField(
            model_name='calculationrun',
            name='chart_v_t_return',
        ),
    ]
