# Generated by Django 6.0.3 on 2026-03-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0012_remove_calculationrun_chart_a_t_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationrun',
            name='chart_forces_main_return',
        ),
    ]
