# Generated by Django 6.0.3 on 2026-04-01 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0013_remove_calculationrun_chart_forces_main_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(default='2.0', max_length=32)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('analysis_snapshot', models.JSONField(blank=True, default=dict)),
                ('thermal_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='recoil_app.calculationrun')),
            ],
            options={
                'verbose_name': 'Снимок расчёта',
                'verbose_name_plural': 'Снимки расчётов',
            },
        ),
    ]
