# Generated by Django 6.0.3 on 2026-04-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0014_calculationsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magneticbrakeconfig',
            options={'ordering': ['run', 'index'], 'verbose_name': 'Магнитный тормоз', 'verbose_name_plural': 'Магнитные тормоза'},
        ),
        migrations.AddField(
            model_name='magneticbrakeconfig',
            name='model_type',
            field=models.CharField(choices=[('parametric', 'Параметрический'), ('curve', 'По графику F(v)')], default='parametric', max_length=16),
        ),
        migrations.AddField(
            model_name='magneticbrakeconfig',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='bz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='dh1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='dh2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='dm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='gamma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='lya',
            field=models.FloatField(blank=True, default=2.5, null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='mu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='wn0',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='xm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='ym',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='magneticbrakeconfig',
            unique_together={('run', 'index')},
        ),
        migrations.CreateModel(
            name='BrakeForcePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('velocity', models.FloatField()),
                ('force', models.FloatField()),
                ('brake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='force_points', to='recoil_app.magneticbrakeconfig')),
            ],
            options={
                'verbose_name': 'Точка характеристики тормоза',
                'verbose_name_plural': 'Точки характеристики тормоза',
                'ordering': ['brake', 'order', 'id'],
                'unique_together': {('brake', 'order')},
            },
        ),
    ]
