# Generated by Django 6.0.3 on 2026-04-04 19:34

import recoil_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0015_alter_magneticbrakeconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magneticbrakeconfig',
            name='curve_file',
            field=models.FileField(blank=True, null=True, upload_to=recoil_app.models.brake_curve_upload_to),
        ),
    ]
