# Generated by Django 6.0.3 on 2026-05-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0018_brake_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brakecatalog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='delta',
            field=models.FloatField(blank=True, help_text='Квадратичный коэффициент δ', null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='gamma',
            field=models.FloatField(blank=True, help_text='Линейный коэффициент γ', null=True),
        ),
        migrations.AlterField(
            model_name='magneticbrakeconfig',
            name='n',
            field=models.IntegerField(blank=True, help_text='Число секций', null=True),
        ),
    ]
