# Generated by Django 6.0.3 on 2026-05-06 09:10

import django.db.models.deletion
import recoil_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoil_app', '0019_alter_brakecatalog_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network_preset', models.CharField(choices=[('nine_node', '9-узловая сеть'), ('single_node', 'Упрощённая (1 узел/тормоз)')], default='nine_node', max_length=16)),
                ('repetitions', models.PositiveIntegerField(default=1)),
                ('pause_s', models.FloatField(default=0.0)),
                ('max_temp_c', models.FloatField(blank=True, null=True)),
                ('max_temp_node_name', models.CharField(blank=True, default='', max_length=120)),
                ('total_heat_j', models.FloatField(blank=True, null=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('warnings_text', models.TextField(blank=True, default='')),
                ('chart_temperatures', models.FileField(blank=True, null=True, upload_to=recoil_app.models.thermal_report_upload_to)),
                ('chart_power_brakes', models.FileField(blank=True, null=True, upload_to=recoil_app.models.thermal_report_upload_to)),
                ('chart_heat_brakes', models.FileField(blank=True, null=True, upload_to=recoil_app.models.thermal_report_upload_to)),
                ('chart_cycle_envelope', models.FileField(blank=True, null=True, upload_to=recoil_app.models.thermal_report_upload_to)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermal_runs', to='recoil_app.calculationrun')),
            ],
            options={
                'verbose_name': 'Тепловой сценарий',
                'verbose_name_plural': 'Тепловые сценарии',
                'ordering': ['-created_at'],
                'unique_together': {('run', 'name')},
            },
        ),
    ]
